# Generated by Django 5.2.4 on 2026-03-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_oj_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
