# Generated by Django 5.2.4 on 2026-03-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_problem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='testcase',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
