# Generated by Django 5.2.4 on 2026-03-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvote_total',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='upvote_total',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
